using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Club.Models.Entities;

namespace Club.Models.Context
{
    public static class SampleData

    {

        public static List<Event> SampleEvents = new List<Event>()
        {
           new Event { Name = "VxFS", Description = "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.", Location = "BÃ©lel", Start = DateTime.Parse("2015-09-01T05:56:44Z") },
new Event { Name = "DXL", Description = "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.", Location = "Tabwakea Village", Start = DateTime.Parse("2015-07-05T09:05:17Z") },
new Event { Name = "Working at Height", Description = "Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.", Location = "Pasacao", Start = DateTime.Parse("2015-09-28T12:38:09Z") },
new Event { Name = "Climate Change", Description = "Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.", Location = "Debar", Start = DateTime.Parse("2015-09-05T09:18:14Z") },
new Event { Name = "OnQ", Description = "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.", Location = "Zumarraga", Start = DateTime.Parse("2016-01-14T17:04:43Z") },
new Event { Name = "NX-OS", Description = "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.", Location = "Boychinovtsi", Start = DateTime.Parse("2015-07-30T15:05:23Z") },
new Event { Name = "Nokia Qt", Description = "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.", Location = "Mojomulyokrajan", Start = DateTime.Parse("2015-11-18T20:27:04Z") },
new Event { Name = "OSI Model", Description = "In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.", Location = "Priboj", Start = DateTime.Parse("2015-12-28T16:23:49Z") },
new Event { Name = "Okuma", Description = "Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.", Location = "Reinaldes", Start = DateTime.Parse("2015-08-06T02:38:00Z") },
new Event { Name = "Grant Writing", Description = "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.", Location = "Ãno KÃ³mi", Start = DateTime.Parse("2015-07-18T16:42:48Z") },
new Event { Name = "UC4", Description = "Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.", Location = "Bom Jesus dos PerdÃµes", Start = DateTime.Parse("2015-09-07T06:19:37Z") },
new Event { Name = "Smoking Cessation", Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.", Location = "DeÃ¡n Funes", Start = DateTime.Parse("2015-10-19T12:49:14Z") },
new Event { Name = "Liability", Description = "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.", Location = "SycÃ³w", Start = DateTime.Parse("2015-09-05T08:09:58Z") },
new Event { Name = "Sea Kayaking", Description = "Suspendisse accumsan tortor quis turpis. Sed ante.", Location = "Kurbnesh", Start = DateTime.Parse("2015-10-15T16:42:39Z") },
new Event { Name = "UK Bribery Act", Description = "Donec dapibus. Duis at velit eu est congue elementum.", Location = "MÃ¼nchen", Start = DateTime.Parse("2015-10-13T03:03:33Z") },
new Event { Name = "Listings", Description = "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.", Location = "Tall á¸¨amÄ«s", Start = DateTime.Parse("2015-11-09T18:54:40Z") },
new Event { Name = "IEEE standards", Description = "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.", Location = "Dukuhmencek Lor", Start = DateTime.Parse("2015-11-10T16:05:58Z") },
new Event { Name = "Internal Controls", Description = "Morbi a ipsum.", Location = "Jianfeng", Start = DateTime.Parse("2015-10-06T08:15:10Z") },
new Event { Name = "Medical Affairs", Description = "Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.", Location = "Buenos Aires", Start = DateTime.Parse("2015-09-10T15:26:15Z") },
new Event { Name = "Oracle OLAP", Description = "Ut tellus. Nulla ut erat id mauris vulputate elementum.", Location = "ConcepciÃ³n", Start = DateTime.Parse("2015-08-27T08:19:40Z") },
new Event { Name = "OSHA 10-Hour", Description = "Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.", Location = "Zselickislak", Start = DateTime.Parse("2015-10-22T18:18:28Z") },
new Event { Name = "HR Policy Formulation", Description = "Aliquam sit amet diam in magna bibendum imperdiet.", Location = "Å»arki", Start = DateTime.Parse("2015-12-04T03:44:35Z") },
new Event { Name = "Retail Banking", Description = "Curabitur in libero ut massa volutpat convallis.", Location = "El Pino", Start = DateTime.Parse("2015-08-12T02:35:31Z") },
new Event { Name = "Hotel Booking", Description = "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.", Location = "Gingsir", Start = DateTime.Parse("2015-10-03T20:28:44Z") },
new Event { Name = "Interior Architecture", Description = "Nulla ac enim.", Location = "ThÃ nh Phá»‘ Háº¡ Long", Start = DateTime.Parse("2015-09-15T12:25:25Z") },
new Event { Name = "IBS", Description = "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.", Location = "Quáº£ng NgÃ£i", Start = DateTime.Parse("2015-11-29T17:07:56Z") },
new Event { Name = "JConsole", Description = "Praesent id massa id nisl venenatis lacinia.", Location = "Jembe Timur", Start = DateTime.Parse("2015-07-30T13:52:47Z") },
new Event { Name = "Forecasting", Description = "Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.", Location = "VranÃ© nad Vltavou", Start = DateTime.Parse("2015-12-22T20:01:29Z") },
new Event { Name = "Lubrication", Description = "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.", Location = "Langqi", Start = DateTime.Parse("2015-12-02T16:08:18Z") },
new Event { Name = "Slip &amp; Fall", Description = "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.", Location = "Masinloc", Start = DateTime.Parse("2015-10-01T23:17:22Z") },
new Event { Name = "WSH", Description = "Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.", Location = "Acheng", Start = DateTime.Parse("2015-12-23T17:51:54Z") },
new Event { Name = "HttpUnit", Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.", Location = "Yumbel", Start = DateTime.Parse("2015-08-02T09:36:47Z") },
new Event { Name = "Food Preparation", Description = "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.", Location = "Shahumyan", Start = DateTime.Parse("2015-11-30T20:07:48Z") },
new Event { Name = "MCT", Description = "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.", Location = "Sawahan", Start = DateTime.Parse("2015-10-30T11:51:38Z") },
new Event { Name = "Hiring", Description = "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.", Location = "Bjuv", Start = DateTime.Parse("2015-10-26T00:46:15Z") },
new Event { Name = "WCCP", Description = "Vestibulum sed magna at nunc commodo placerat.", Location = "Oleksandriya", Start = DateTime.Parse("2015-12-10T14:45:44Z") },
new Event { Name = "SAP-SD", Description = "Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.", Location = "Lyaskovets", Start = DateTime.Parse("2016-01-11T03:10:12Z") },
new Event { Name = "Forklift Operation", Description = "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.", Location = "La Gloria", Start = DateTime.Parse("2015-10-23T18:36:19Z") },
new Event { Name = "Ice Cream", Description = "Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.", Location = "Pinaring", Start = DateTime.Parse("2016-01-14T07:56:31Z") },
new Event { Name = "Ulcerative Colitis", Description = "Aenean sit amet justo.", Location = "Kanda", Start = DateTime.Parse("2015-12-09T09:35:04Z") },
new Event { Name = "High Performance Computing", Description = "Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.", Location = "Kiszkowo", Start = DateTime.Parse("2015-09-04T19:22:18Z") },
new Event { Name = "Pro-IV", Description = "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.", Location = "Madamba", Start = DateTime.Parse("2015-09-14T03:36:35Z") },
new Event { Name = "PMB", Description = "Sed accumsan felis.", Location = "Gagarawa", Start = DateTime.Parse("2015-10-05T19:16:15Z") },
new Event { Name = "NGN", Description = "Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.", Location = "Kawahmanuk", Start = DateTime.Parse("2016-01-10T03:04:23Z") },
new Event { Name = "YSlow", Description = "Aenean lectus.", Location = "SinÅ­iju", Start = DateTime.Parse("2015-11-28T22:39:51Z") },
new Event { Name = "SIP", Description = "Integer tincidunt ante vel ipsum.", Location = "Xiaohebian", Start = DateTime.Parse("2015-10-07T16:20:29Z") },
new Event { Name = "DFT Compiler", Description = "Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.", Location = "Somdet", Start = DateTime.Parse("2015-10-17T13:19:03Z") },
new Event { Name = "AAP", Description = "Pellentesque at nulla. Suspendisse potenti.", Location = "NovÃ© MÄ›sto nad MetujÃ­", Start = DateTime.Parse("2015-10-03T19:04:08Z") },
new Event { Name = "Erwin", Description = "Phasellus sit amet erat.", Location = "Semiring", Start = DateTime.Parse("2015-09-02T12:06:45Z") },
new Event { Name = "HMI Design", Description = "Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.", Location = "Haicheng", Start = DateTime.Parse("2016-01-10T21:02:34Z") },
new Event { Name = "Sketching", Description = "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.", Location = "Cinyawang", Start = DateTime.Parse("2015-09-20T17:52:53Z") },
new Event { Name = "NDIS", Description = "Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.", Location = "Kupang", Start = DateTime.Parse("2015-08-18T10:56:40Z") },
new Event { Name = "PKI", Description = "Etiam faucibus cursus urna. Ut tellus.", Location = "Gongji", Start = DateTime.Parse("2015-09-28T11:44:37Z") },
new Event { Name = "Microsoft SQL Server", Description = "Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.", Location = "Tegalalang", Start = DateTime.Parse("2015-09-16T10:36:37Z") },
new Event { Name = "NGN", Description = "Integer ac neque.", Location = "Bom Sucesso", Start = DateTime.Parse("2015-12-30T11:23:05Z") },
new Event { Name = "EOL", Description = "Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.", Location = "Sambirejo", Start = DateTime.Parse("2016-01-09T09:45:24Z") },
new Event { Name = "OWL", Description = "Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.", Location = "Jiangjiazui", Start = DateTime.Parse("2015-11-04T03:49:47Z") },
new Event { Name = "Medical Affairs", Description = "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.", Location = "Marseille", Start = DateTime.Parse("2015-12-18T01:57:37Z") },
new Event { Name = "CTRS", Description = "Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.", Location = "WaddÄn", Start = DateTime.Parse("2015-08-30T11:24:41Z") },
new Event { Name = "DHTML", Description = "Nulla facilisi. Cras non velit nec nisi vulputate nonummy.", Location = "Mandikbatu", Start = DateTime.Parse("2015-08-24T03:01:40Z") },
new Event { Name = "Music Videos", Description = "Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.", Location = "NÃ©os MylÃ³topos", Start = DateTime.Parse("2015-07-22T11:44:31Z") },
new Event { Name = "CCDP", Description = "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.", Location = "Nangxian", Start = DateTime.Parse("2015-11-22T05:39:21Z") },
new Event { Name = "NYMEX", Description = "Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.", Location = "Tak Bai", Start = DateTime.Parse("2015-08-25T04:26:17Z") },
new Event { Name = "Troubleshooting", Description = "Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.", Location = "Mankono", Start = DateTime.Parse("2015-10-17T16:55:33Z") },
new Event { Name = "WSRR", Description = "Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.", Location = "Slavyanovo", Start = DateTime.Parse("2015-12-06T14:16:02Z") },
new Event { Name = "Hair Care", Description = "Duis mattis egestas metus. Aenean fermentum.", Location = "Krasnyy Oktyabrâ€™", Start = DateTime.Parse("2015-08-11T17:46:24Z") },
new Event { Name = "Xactly", Description = "Nulla tellus.", Location = "Choros", Start = DateTime.Parse("2015-09-30T07:36:36Z") },
new Event { Name = "Medical Billing", Description = "Sed ante. Vivamus tortor. Duis mattis egestas metus.", Location = "Kudang", Start = DateTime.Parse("2016-01-19T19:42:57Z") },
new Event { Name = "Dell KACE", Description = "Nulla nisl. Nunc nisl.", Location = "StrÃ¶msund", Start = DateTime.Parse("2015-09-24T07:32:01Z") },
new Event { Name = "Field Work", Description = "Etiam faucibus cursus urna. Ut tellus.", Location = "Jistebnice", Start = DateTime.Parse("2015-12-10T01:47:48Z") },
new Event { Name = "MMR", Description = "In sagittis dui vel nisl. Duis ac nibh.", Location = "Zephyrhills", Start = DateTime.Parse("2016-01-10T02:13:19Z") },
new Event { Name = "Pastoral Care", Description = "Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.", Location = "Al Aá¸©madÄ«", Start = DateTime.Parse("2015-09-24T00:06:17Z") },
new Event { Name = "Private Duty", Description = "Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.", Location = "Vogar", Start = DateTime.Parse("2015-08-03T18:12:25Z") },
new Event { Name = "QSE", Description = "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.", Location = "Rzhev", Start = DateTime.Parse("2016-01-18T06:40:53Z") },
new Event { Name = "Photojournalism", Description = "Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.", Location = "BÃ©kÃ©scsaba", Start = DateTime.Parse("2015-11-08T10:11:06Z") },
new Event { Name = "Eplan", Description = "In hac habitasse platea dictumst.", Location = "Chaihe", Start = DateTime.Parse("2015-11-09T15:05:00Z") },
new Event { Name = "RFID Applications", Description = "Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.", Location = "Taldyqorghan", Start = DateTime.Parse("2015-08-12T14:55:59Z") },
new Event { Name = "Corporate FP&amp;A", Description = "Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.", Location = "Mikhaylovka", Start = DateTime.Parse("2015-10-30T21:48:16Z") },
new Event { Name = "Rock Mechanics", Description = "Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.", Location = "Gasa", Start = DateTime.Parse("2015-11-15T00:02:19Z") },
new Event { Name = "Abstracting", Description = "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.", Location = "La Concepcion", Start = DateTime.Parse("2016-01-02T04:47:24Z") },
new Event { Name = "Certified EKG Technician", Description = "Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.", Location = "Marhanetsâ€™", Start = DateTime.Parse("2016-01-10T01:27:08Z") },
new Event { Name = "Yin Yoga", Description = "Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.", Location = "Los Pinos", Start = DateTime.Parse("2015-10-03T08:54:42Z") },
new Event { Name = "Property Management Systems", Description = "Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.", Location = "Lille", Start = DateTime.Parse("2015-08-04T17:13:09Z") },
new Event { Name = "Pulse Oximetry", Description = "Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.", Location = "Cikole", Start = DateTime.Parse("2016-01-11T18:49:52Z") },
new Event { Name = "Hair Cutting", Description = "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.", Location = "Baoxing", Start = DateTime.Parse("2015-07-26T03:00:20Z") },
new Event { Name = "VLAN", Description = "Curabitur at ipsum ac tellus semper interdum.", Location = "Ã…tvidaberg", Start = DateTime.Parse("2015-07-11T01:19:45Z") },
new Event { Name = "Organizational Effectiveness", Description = "Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.", Location = "Tekeli", Start = DateTime.Parse("2015-12-09T12:52:14Z") },
new Event { Name = "RCSA", Description = "Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.", Location = "Bagjasari", Start = DateTime.Parse("2015-11-15T05:38:16Z") },
new Event { Name = "Outplacement", Description = "Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.", Location = "QarÄwul", Start = DateTime.Parse("2015-12-08T03:40:18Z") },
new Event { Name = "Litigation", Description = "Nullam porttitor lacus at turpis.", Location = "Daliu", Start = DateTime.Parse("2015-12-11T15:35:24Z") },
new Event { Name = "OData", Description = "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.", Location = "Binguang", Start = DateTime.Parse("2015-08-29T19:45:10Z") },
new Event { Name = "Yard Signs", Description = "Aenean sit amet justo. Morbi ut odio.", Location = "Nyanza", Start = DateTime.Parse("2015-09-14T18:34:20Z") },
new Event { Name = "RDz", Description = "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.", Location = "ChaviÃ±a", Start = DateTime.Parse("2016-01-14T01:10:32Z") },
new Event { Name = "CTF", Description = "Etiam vel augue.", Location = "Fraga", Start = DateTime.Parse("2015-10-25T23:30:29Z") },
new Event { Name = "HCV", Description = "Proin risus.", Location = "ValenÃ§a do Douro", Start = DateTime.Parse("2015-12-26T04:03:44Z") },
new Event { Name = "ISO 22000", Description = "In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.", Location = "Gombe", Start = DateTime.Parse("2015-11-09T21:41:59Z") },
new Event { Name = "Tutoring", Description = "Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.", Location = "Borzna", Start = DateTime.Parse("2015-07-13T12:46:26Z") },
new Event { Name = "Compensation &amp; Benefits", Description = "Etiam faucibus cursus urna.", Location = "Herzliya Pituah", Start = DateTime.Parse("2015-12-23T11:09:02Z") },
new Event { Name = "Qt Creator", Description = "Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.", Location = "Rosh Pinna", Start = DateTime.Parse("2015-07-25T07:57:05Z") },
new Event { Name = "JDF", Description = "Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.", Location = "KoÄevje", Start = DateTime.Parse("2015-08-22T06:40:47Z") },


        };

        public static List<Announcement> SampleAnnouncements = new List<Announcement>()
        {
            new Announcement { Name= "Proin vel nisl.", Text = "ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec", DueDate = DateTime.Parse("2016-01-25T05:10:28-08:00"), IsPrivate = 1 % 2 == 0  },
new Announcement { Name= "at, velit.", Text = "molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat", DueDate = DateTime.Parse("2016-01-22T09:15:09-08:00"), IsPrivate = 2 % 2 == 0  },
new Announcement { Name= "Nulla", Text = "odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam", DueDate = DateTime.Parse("2016-01-29T09:52:42-08:00"), IsPrivate = 10 % 2 == 0  },
new Announcement { Name= "in, hendrerit", Text = "venenatis lacus. Etiam bibendum fermentum", DueDate = DateTime.Parse("2016-01-28T21:03:27-08:00"), IsPrivate = 1 % 2 == 0  },
new Announcement { Name= "Donec dignissim", Text = "nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at,", DueDate = DateTime.Parse("2016-01-27T03:48:45-08:00"), IsPrivate = 9 % 2 == 0  },
new Announcement { Name= "Mauris vestibulum,", Text = "Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in,", DueDate = DateTime.Parse("2016-01-24T23:11:11-08:00"), IsPrivate = 10 % 2 == 0  },
new Announcement { Name= "Proin sed turpis", Text = "ut ipsum ac mi eleifend egestas. Sed pharetra,", DueDate = DateTime.Parse("2016-01-20T09:03:37-08:00"), IsPrivate = 9 % 2 == 0  },
new Announcement { Name= "et arcu imperdiet", Text = "Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus,", DueDate = DateTime.Parse("2016-01-27T13:28:40-08:00"), IsPrivate = 8 % 2 == 0  },
new Announcement { Name= "nisl.", Text = "dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla,", DueDate = DateTime.Parse("2016-01-29T02:50:53-08:00"), IsPrivate = 6 % 2 == 0  },
new Announcement { Name= "sagittis semper. Nam", Text = "nunc sed", DueDate = DateTime.Parse("2016-01-29T16:52:54-08:00"), IsPrivate = 6 % 2 == 0  },
new Announcement { Name= "nunc nulla", Text = "metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer", DueDate = DateTime.Parse("2016-01-27T12:58:11-08:00"), IsPrivate = 6 % 2 == 0  },
new Announcement { Name= "vitae,", Text = "Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin", DueDate = DateTime.Parse("2016-01-24T14:52:27-08:00"), IsPrivate = 9 % 2 == 0  },
new Announcement { Name= "lectus", Text = "convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a,", DueDate = DateTime.Parse("2016-01-26T21:15:34-08:00"), IsPrivate = 8 % 2 == 0  },
new Announcement { Name= "ornare.", Text = "placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue", DueDate = DateTime.Parse("2016-01-20T05:09:21-08:00"), IsPrivate = 6 % 2 == 0  },
new Announcement { Name= "nec enim. Nunc", Text = "ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices,", DueDate = DateTime.Parse("2016-01-29T02:18:56-08:00"), IsPrivate = 8 % 2 == 0  },
new Announcement { Name= "turpis non enim.", Text = "enim, gravida sit amet, dapibus id,", DueDate = DateTime.Parse("2016-01-22T14:41:02-08:00"), IsPrivate = 1 % 2 == 0  },
new Announcement { Name= "nibh. Quisque", Text = "nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper,", DueDate = DateTime.Parse("2016-01-28T08:28:01-08:00"), IsPrivate = 8 % 2 == 0  },
new Announcement { Name= "sapien.", Text = "sed orci lobortis augue scelerisque", DueDate = DateTime.Parse("2016-01-21T16:21:20-08:00"), IsPrivate = 4 % 2 == 0  },

        };

        public static List<ClubUser> SampleClubUsers = new List<ClubUser>()
        {
            new ClubUser { UserName = "OLh743uUt", Approved=true, Email ="ullamcorper@dolorquamelementum.net", FirstName = "Stone", LastName = "Rocha" },
            new ClubUser { UserName = "VJy777uEZ", Approved=true, Email ="ligula.eu.enim@adipiscing.edu", FirstName = "Randall", LastName = "Woodward" },
            new ClubUser { UserName = "xQT897ooJ", Approved=true, Email ="diam@Nulla.edu", FirstName = "Orlando", LastName = "Woods" },
            new ClubUser { UserName = "YXW219uEQ", Approved=false, Email ="interdum.enim.non@euismodestarcu.net", FirstName = "Alden", LastName = "Simpson" },
            new ClubUser { UserName = "mDK381UOl", Approved=false, Email ="Maecenas.libero@ettristiquepellentesque.net", FirstName = "Nita", LastName = "Wilkerson" },
            new ClubUser { UserName = "qPQ575IEC", Approved=false, Email ="Nunc.commodo@felis.ca", FirstName = "Petra", LastName = "Frazier" },
            new ClubUser { UserName = "qNt54FoON", Approved=true, Email ="mollis@tincidunt.com", FirstName = "Serina", LastName = "Cardenas" },
            new ClubUser { UserName = "eJV83EAET", Approved=true, Email ="nec.cursus@tortornibh.com", FirstName = "Noble", LastName = "Keller" },
            new ClubUser { UserName = "vQZ40FOUF", Approved=true, Email ="eu.tellus.eu@sitamet.edu", FirstName = "Quemby", LastName = "Meyers" },
            new ClubUser { UserName = "FPZ67Aiim", Approved=false, Email ="elit.fermentum.risus@ornare.org", FirstName = "Castor", LastName = "Mathis" },
            new ClubUser { UserName = "JHb467eab", Approved=false, Email ="libero.nec.ligula@telluslorem.ca", FirstName = "Roanna", LastName = "Gilliam" },
            new ClubUser { UserName = "ANt881aEx", Approved=false, Email ="mollis@risusquisdiam.ca", FirstName = "Marshall", LastName = "Johns" },
            new ClubUser { UserName = "IJj516aUk", Approved=true, Email ="amet.risus.Donec@risusQuisque.com", FirstName = "Clarke", LastName = "Horton" },
            new ClubUser { UserName = "UZp169OuN", Approved=true, Email ="non.justo@nec.org", FirstName = "Natalie", LastName = "Terry" },
            new ClubUser { UserName = "pDj48BIEs", Approved=true, Email ="quam.dignissim@ullamcorperviverra.org", FirstName = "Jorden", LastName = "Calhoun" },
            new ClubUser { UserName = "VHS999IeD", Approved=false, Email ="Aenean.gravida.nunc@DonecfringillaDonec.org", FirstName = "Sybil", LastName = "Calhoun" },
            new ClubUser { UserName = "hWb79Eeor", Approved=false, Email ="tincidunt.adipiscing.Mauris@amet.net", FirstName = "Rhonda", LastName = "Wall" },
            new ClubUser { UserName = "RMH512EUX", Approved=false, Email ="vulputate.eu.odio@a.ca", FirstName = "Aphrodite", LastName = "Solomon" },
            new ClubUser { UserName = "MNc99CAeZ", Approved=true, Email ="tincidunt@lectusa.org", FirstName = "Cecilia", LastName = "Mckinney" },
            new ClubUser { UserName = "JGf40FEod", Approved=true, Email ="nisi@netusetmalesuada.com", FirstName = "Lucian", LastName = "Conner" },
            new ClubUser { UserName = "DPW115OEL", Approved=true, Email ="enim.consequat@Nuncullamcorpervelit.ca", FirstName = "Clayton", LastName = "Huffman" },
            new ClubUser { UserName = "SZt59DOej", Approved=false, Email ="Aliquam.vulputate.ullamcorper@et.ca", FirstName = "Chancellor", LastName = "Chapman" },
            new ClubUser { UserName = "JLN13EeeB", Approved=false, Email ="penatibus.et.magnis@ornarelectusjusto.ca", FirstName = "Nehru", LastName = "David" },
            new ClubUser { UserName = "vGk171AUD", Approved=false, Email ="Nunc@lacinia.net", FirstName = "James", LastName = "Salas" },
            new ClubUser { UserName = "qCD281UuF", Approved=true, Email ="nulla.Integer@accumsanlaoreetipsum.com", FirstName = "Nelle", LastName = "Carpenter" },
            new ClubUser { UserName = "oHP39FEaK", Approved=true, Email ="orci.luctus@Mauris.net", FirstName = "Phillip", LastName = "Harrington" },
            new ClubUser { UserName = "fMr762uiv", Approved=true, Email ="eu@sodales.co.uk", FirstName = "Willa", LastName = "Fernandez" },
            new ClubUser { UserName = "pRb152AeW", Approved=false, Email ="Fusce.mollis@etarcuimperdiet.net", FirstName = "Orli", LastName = "Rocha" },
            new ClubUser { UserName = "fSf57EIeh", Approved=false, Email ="Donec.egestas@ullamcorper.co.uk", FirstName = "Amethyst", LastName = "Morrison" },
            new ClubUser { UserName = "iQT944ooz", Approved=false, Email ="erat.vitae@sitametdapibus.edu", FirstName = "Teagan", LastName = "Richard" },
            new ClubUser { UserName = "rVV431UuG", Approved=true, Email ="vitae.velit.egestas@Maecenasiaculisaliquet.org", FirstName = "Blythe", LastName = "Chase" },
            new ClubUser { UserName = "TJY63BiaN", Approved=true, Email ="et@Aliquamultricesiaculis.org", FirstName = "Adrian", LastName = "Soto" },
            new ClubUser { UserName = "WHm124uuT", Approved=true, Email ="non@felisorci.org", FirstName = "Justine", LastName = "Crawford" },
            new ClubUser { UserName = "bLH98DUIm", Approved=false, Email ="Donec@Aliquamgravidamauris.org", FirstName = "Damian", LastName = "Terrell" },
            new ClubUser { UserName = "xFm902eig", Approved=false, Email ="magnis.dis.parturient@turpisIncondimentum.ca", FirstName = "Daniel", LastName = "Rollins" },
            new ClubUser { UserName = "eSw53DIUn", Approved=false, Email ="a@Cum.com", FirstName = "Phyllis", LastName = "Emerson" },
            new ClubUser { UserName = "BFV921uiT", Approved=true, Email ="lobortis@auctor.edu", FirstName = "Gavin", LastName = "Jennings" },
            new ClubUser { UserName = "BSm310OaN", Approved=true, Email ="quis@tortornibh.edu", FirstName = "Aquila", LastName = "Barrett" },
            new ClubUser { UserName = "mGj74BIoz", Approved=true, Email ="Integer.urna.Vivamus@ac.net", FirstName = "Sean", LastName = "Riggs" },
            new ClubUser { UserName = "BKF213AEY", Approved=false, Email ="Donec@necorciDonec.ca", FirstName = "Ryder", LastName = "Delacruz" },
            new ClubUser { UserName = "HQp81EAig", Approved=false, Email ="ante.ipsum.primis@laoreetlectus.net", FirstName = "Yoko", LastName = "Farmer" },
            new ClubUser { UserName = "HRj86CaEz", Approved=false, Email ="volutpat.Nulla@Donec.co.uk", FirstName = "Bertha", LastName = "Mullins" },
            new ClubUser { UserName = "pRs641uuM", Approved=true, Email ="velit.eu.sem@necligulaconsectetuer.com", FirstName = "Walter", LastName = "Sanchez" },
            new ClubUser { UserName = "OXB902OaR", Approved=true, Email ="sed@Integeridmagna.ca", FirstName = "Kendall", LastName = "Cain" },
            new ClubUser { UserName = "lLr18CeIf", Approved=true, Email ="auctor@nonjustoProin.ca", FirstName = "Urielle", LastName = "Barber" },
            new ClubUser { UserName = "GTG78Bioq", Approved=false, Email ="a.odio@euerat.org", FirstName = "Flavia", LastName = "Tillman" },
            new ClubUser { UserName = "jCS215uAp", Approved=false, Email ="enim.diam@turpis.ca", FirstName = "Gary", LastName = "Murray" },
            new ClubUser { UserName = "VGy280aeQ", Approved=false, Email ="Nullam.enim@etliberoProin.edu", FirstName = "Duncan", LastName = "Ellis" },
            new ClubUser { UserName = "SCN446IeV", Approved=true, Email ="est@laciniamattisInteger.ca", FirstName = "Ava", LastName = "Perry" },
            new ClubUser { UserName = "kNz71DoaZ", Approved=true, Email ="tempus.eu.ligula@semper.edu", FirstName = "Amela", LastName = "Anderson" },
            new ClubUser { UserName = "ySn873UeB", Approved=true, Email ="montes.nascetur.ridiculus@eu.net", FirstName = "Amery", LastName = "Rhodes" },
            new ClubUser { UserName = "hLk63BuIh", Approved=false, Email ="urna@nuncest.co.uk", FirstName = "Latifah", LastName = "Hicks" },
            new ClubUser { UserName = "jLk951aiS", Approved=false, Email ="scelerisque.mollis@tinciduntadipiscingMauris.ca", FirstName = "Dane", LastName = "Odonnell" },
            new ClubUser { UserName = "PQb61EeOx", Approved=false, Email ="massa.Mauris@Cumsociisnatoque.net", FirstName = "Tyler", LastName = "Murphy" },
            new ClubUser { UserName = "qZg758UeB", Approved=true, Email ="tortor.Nunc.commodo@nisiAenean.edu", FirstName = "Yael", LastName = "Holman" },
            new ClubUser { UserName = "JLx50FAUf", Approved=true, Email ="amet.faucibus.ut@elitCurabitur.net", FirstName = "Sonia", LastName = "Collier" },
            new ClubUser { UserName = "yWz963OOS", Approved=true, Email ="Curabitur@in.co.uk", FirstName = "Quinn", LastName = "Mays" },
            new ClubUser { UserName = "uWz337AID", Approved=false, Email ="nec.tellus@Vivamusnibhdolor.org", FirstName = "Noel", LastName = "Grant" },
            new ClubUser { UserName = "eSj602UUc", Approved=false, Email ="sit.amet.ornare@urnaNuncquis.org", FirstName = "Ferris", LastName = "Swanson" },
            new ClubUser { UserName = "oBq281EAM", Approved=false, Email ="mauris.ipsum@eteuismod.net", FirstName = "Kessie", LastName = "Duncan" },
            new ClubUser { UserName = "LXb360uot", Approved=true, Email ="sapien@velmaurisInteger.org", FirstName = "Cruz", LastName = "Thompson" },
            new ClubUser { UserName = "XGz349auz", Approved=true, Email ="vestibulum@vitaedolorDonec.com", FirstName = "Imani", LastName = "Evans" },
            new ClubUser { UserName = "TWJ656aER", Approved=true, Email ="et.ultrices@velitSedmalesuada.net", FirstName = "Levi", LastName = "Crane" },
            new ClubUser { UserName = "OJR74Ciiq", Approved=false, Email ="molestie.pharetra.nibh@ornareplaceratorci.com", FirstName = "Daria", LastName = "Kline" },
            new ClubUser { UserName = "EDD64EOoc", Approved=false, Email ="ligula.eu@ametnulla.org", FirstName = "Carissa", LastName = "Hendricks" },
            new ClubUser { UserName = "TSj883aAv", Approved=false, Email ="tristique.pharetra.Quisque@estNunc.com", FirstName = "Xavier", LastName = "Koch" },
            new ClubUser { UserName = "NWV78AiAH", Approved=true, Email ="Sed@lobortisaugue.com", FirstName = "Aimee", LastName = "Mayo" },
            new ClubUser { UserName = "yHm55AuAp", Approved=true, Email ="non.massa.non@turpisnec.org", FirstName = "Holly", LastName = "Walters" },
            new ClubUser { UserName = "BFd636eeG", Approved=true, Email ="elit.dictum.eu@faucibus.net", FirstName = "Felix", LastName = "Marks" },
            new ClubUser { UserName = "kSD419UAb", Approved=false, Email ="ullamcorper@et.edu", FirstName = "Connor", LastName = "Clarke" },
            new ClubUser { UserName = "SDk462EoS", Approved=false, Email ="nec.mauris.blandit@Inat.co.uk", FirstName = "Venus", LastName = "Kemp" },
            new ClubUser { UserName = "zCQ100Iib", Approved=false, Email ="amet.consectetuer.adipiscing@pharetraNamac.edu", FirstName = "Clark", LastName = "Wise" },
            new ClubUser { UserName = "xLn433eUx", Approved=true, Email ="lacinia@aliquamenim.org", FirstName = "Basil", LastName = "Mclaughlin" },
            new ClubUser { UserName = "nKp727aoc", Approved=true, Email ="ante.iaculis@Nullasemper.edu", FirstName = "Eden", LastName = "Harrison" },
            new ClubUser { UserName = "vGw460uut", Approved=true, Email ="et.magnis@gravidasitamet.co.uk", FirstName = "Oleg", LastName = "Carr" },
            new ClubUser { UserName = "tQF535Auh", Approved=false, Email ="aliquet.nec@Integereu.com", FirstName = "Lev", LastName = "Rivers" },
            new ClubUser { UserName = "KQs790aaN", Approved=false, Email ="ac@Namacnulla.com", FirstName = "Cassandra", LastName = "Mcgowan" },
            new ClubUser { UserName = "AMF311eef", Approved=false, Email ="amet@eratSednunc.ca", FirstName = "Abigail", LastName = "Glover" },
            new ClubUser { UserName = "xWb738Eor", Approved=true, Email ="lectus@ipsumcursus.ca", FirstName = "Conan", LastName = "Byers" },
            new ClubUser { UserName = "MBb86FoAr", Approved=true, Email ="Donec.tincidunt@Nullam.org", FirstName = "Dora", LastName = "Burnett" },
            new ClubUser { UserName = "xFy984AIF", Approved=true, Email ="ultrices@metus.net", FirstName = "Robin", LastName = "Rodriguez" },
            new ClubUser { UserName = "NSY94AAoy", Approved=false, Email ="euismod.in.dolor@nisi.co.uk", FirstName = "Neil", LastName = "Chaney" },
            new ClubUser { UserName = "jNn840iAL", Approved=false, Email ="eu.placerat@diam.co.uk", FirstName = "Jade", LastName = "Velasquez" },
            new ClubUser { UserName = "NFp79BoeV", Approved=false, Email ="vitae@velitdui.edu", FirstName = "Abbot", LastName = "Stein" },
            new ClubUser { UserName = "dMF209UEq", Approved=true, Email ="diam.Pellentesque.habitant@nislNullaeu.edu", FirstName = "Darius", LastName = "Padilla" },
            new ClubUser { UserName = "ZJG73Douk", Approved=true, Email ="ante.bibendum.ullamcorper@nec.com", FirstName = "Nita", LastName = "Bradley" },
            new ClubUser { UserName = "UHS263AOZ", Approved=true, Email ="eros@laciniaSedcongue.edu", FirstName = "Kibo", LastName = "Hoffman" },
            new ClubUser { UserName = "YYV17AIEc", Approved=false, Email ="ac.mattis.velit@malesuada.org", FirstName = "Matthew", LastName = "Todd" },
            new ClubUser { UserName = "XSv595Aux", Approved=false, Email ="Ut@Morbimetus.co.uk", FirstName = "Wyoming", LastName = "Petersen" },
            new ClubUser { UserName = "aTx516oEP", Approved=false, Email ="congue.turpis.In@Aliquamtincidunt.edu", FirstName = "Fleur", LastName = "Daugherty" },
            new ClubUser { UserName = "VWB382AeZ", Approved=true, Email ="sed.dolor.Fusce@idblanditat.ca", FirstName = "Zachary", LastName = "Fleming" },
            new ClubUser { UserName = "cJR534Oec", Approved=true, Email ="ultrices@intempuseu.com", FirstName = "Breanna", LastName = "Downs" },
            new ClubUser { UserName = "bWY67BouN", Approved=true, Email ="Cras.interdum@eueleifendnec.org", FirstName = "Fuller", LastName = "Ray" },
            new ClubUser { UserName = "BJH106Uiv", Approved=false, Email ="ac.mi@bibendum.org", FirstName = "Madonna", LastName = "Armstrong" },
            new ClubUser { UserName = "QBY76FAiF", Approved=false, Email ="venenatis.a@ornare.net", FirstName = "Eve", LastName = "Schmidt" },
            new ClubUser { UserName = "yNn64EIEH", Approved=false, Email ="mi.felis.adipiscing@Donecegestas.org", FirstName = "Buffy", LastName = "Reynolds" },
            new ClubUser { UserName = "QDc158UeN", Approved=true, Email ="malesuada@aliquetliberoInteger.ca", FirstName = "Kuame", LastName = "Garza" },
            new ClubUser { UserName = "gTw575UUC", Approved=true, Email ="vel@pedeac.com", FirstName = "Gemma", LastName = "Moses" },
            new ClubUser { UserName = "sWQ142oIr", Approved=true, Email ="tempus.lorem@ante.edu", FirstName = "Rhiannon", LastName = "Johnston" },
            new ClubUser { UserName = "ASR13EuUP", Approved=false, Email ="vitae.aliquet@convallisantelectus.edu", FirstName = "Francis", LastName = "Patel" },

        };
    }
}
