using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Club.Models.Entities;

namespace Club.Models.Context
{
    public static class SampleData

    {
        public static List<ClubUser> SampleClubUsers = new List<ClubUser>()
        {
            new ClubUser { UserName = "OLh743uUt", Approved=true, Email ="ullamcorper@dolorquamelementum.net", FirstName = "Stone", LastName = "Rocha" },
            new ClubUser { UserName = "VJy777uEZ", Approved=true, Email ="ligula.eu.enim@adipiscing.edu", FirstName = "Randall", LastName = "Woodward" },
            new ClubUser { UserName = "xQT897ooJ", Approved=true, Email ="diam@Nulla.edu", FirstName = "Orlando", LastName = "Woods" },
            new ClubUser { UserName = "YXW219uEQ", Approved=false, Email ="interdum.enim.non@euismodestarcu.net", FirstName = "Alden", LastName = "Simpson" },
            new ClubUser { UserName = "mDK381UOl", Approved=false, Email ="Maecenas.libero@ettristiquepellentesque.net", FirstName = "Nita", LastName = "Wilkerson" },
            new ClubUser { UserName = "qPQ575IEC", Approved=false, Email ="Nunc.commodo@felis.ca", FirstName = "Petra", LastName = "Frazier" },
            new ClubUser { UserName = "qNt54FoON", Approved=true, Email ="mollis@tincidunt.com", FirstName = "Serina", LastName = "Cardenas" },
            new ClubUser { UserName = "eJV83EAET", Approved=true, Email ="nec.cursus@tortornibh.com", FirstName = "Noble", LastName = "Keller" },
            new ClubUser { UserName = "vQZ40FOUF", Approved=true, Email ="eu.tellus.eu@sitamet.edu", FirstName = "Quemby", LastName = "Meyers" },
            new ClubUser { UserName = "FPZ67Aiim", Approved=false, Email ="elit.fermentum.risus@ornare.org", FirstName = "Castor", LastName = "Mathis" },
            new ClubUser { UserName = "JHb467eab", Approved=false, Email ="libero.nec.ligula@telluslorem.ca", FirstName = "Roanna", LastName = "Gilliam" },
            new ClubUser { UserName = "ANt881aEx", Approved=false, Email ="mollis@risusquisdiam.ca", FirstName = "Marshall", LastName = "Johns" },
            new ClubUser { UserName = "IJj516aUk", Approved=true, Email ="amet.risus.Donec@risusQuisque.com", FirstName = "Clarke", LastName = "Horton" },
            new ClubUser { UserName = "UZp169OuN", Approved=true, Email ="non.justo@nec.org", FirstName = "Natalie", LastName = "Terry" },
            new ClubUser { UserName = "pDj48BIEs", Approved=true, Email ="quam.dignissim@ullamcorperviverra.org", FirstName = "Jorden", LastName = "Calhoun" },
            new ClubUser { UserName = "VHS999IeD", Approved=false, Email ="Aenean.gravida.nunc@DonecfringillaDonec.org", FirstName = "Sybil", LastName = "Calhoun" },
            new ClubUser { UserName = "hWb79Eeor", Approved=false, Email ="tincidunt.adipiscing.Mauris@amet.net", FirstName = "Rhonda", LastName = "Wall" },
            new ClubUser { UserName = "RMH512EUX", Approved=false, Email ="vulputate.eu.odio@a.ca", FirstName = "Aphrodite", LastName = "Solomon" },
            new ClubUser { UserName = "MNc99CAeZ", Approved=true, Email ="tincidunt@lectusa.org", FirstName = "Cecilia", LastName = "Mckinney" },
            new ClubUser { UserName = "JGf40FEod", Approved=true, Email ="nisi@netusetmalesuada.com", FirstName = "Lucian", LastName = "Conner" },
            new ClubUser { UserName = "DPW115OEL", Approved=true, Email ="enim.consequat@Nuncullamcorpervelit.ca", FirstName = "Clayton", LastName = "Huffman" },
            new ClubUser { UserName = "SZt59DOej", Approved=false, Email ="Aliquam.vulputate.ullamcorper@et.ca", FirstName = "Chancellor", LastName = "Chapman" },
            new ClubUser { UserName = "JLN13EeeB", Approved=false, Email ="penatibus.et.magnis@ornarelectusjusto.ca", FirstName = "Nehru", LastName = "David" },
            new ClubUser { UserName = "vGk171AUD", Approved=false, Email ="Nunc@lacinia.net", FirstName = "James", LastName = "Salas" },
            new ClubUser { UserName = "qCD281UuF", Approved=true, Email ="nulla.Integer@accumsanlaoreetipsum.com", FirstName = "Nelle", LastName = "Carpenter" },
            new ClubUser { UserName = "oHP39FEaK", Approved=true, Email ="orci.luctus@Mauris.net", FirstName = "Phillip", LastName = "Harrington" },
            new ClubUser { UserName = "fMr762uiv", Approved=true, Email ="eu@sodales.co.uk", FirstName = "Willa", LastName = "Fernandez" },
            new ClubUser { UserName = "pRb152AeW", Approved=false, Email ="Fusce.mollis@etarcuimperdiet.net", FirstName = "Orli", LastName = "Rocha" },
            new ClubUser { UserName = "fSf57EIeh", Approved=false, Email ="Donec.egestas@ullamcorper.co.uk", FirstName = "Amethyst", LastName = "Morrison" },
            new ClubUser { UserName = "iQT944ooz", Approved=false, Email ="erat.vitae@sitametdapibus.edu", FirstName = "Teagan", LastName = "Richard" },
            new ClubUser { UserName = "rVV431UuG", Approved=true, Email ="vitae.velit.egestas@Maecenasiaculisaliquet.org", FirstName = "Blythe", LastName = "Chase" },
            new ClubUser { UserName = "TJY63BiaN", Approved=true, Email ="et@Aliquamultricesiaculis.org", FirstName = "Adrian", LastName = "Soto" },
            new ClubUser { UserName = "WHm124uuT", Approved=true, Email ="non@felisorci.org", FirstName = "Justine", LastName = "Crawford" },
            new ClubUser { UserName = "bLH98DUIm", Approved=false, Email ="Donec@Aliquamgravidamauris.org", FirstName = "Damian", LastName = "Terrell" },
            new ClubUser { UserName = "xFm902eig", Approved=false, Email ="magnis.dis.parturient@turpisIncondimentum.ca", FirstName = "Daniel", LastName = "Rollins" },
            new ClubUser { UserName = "eSw53DIUn", Approved=false, Email ="a@Cum.com", FirstName = "Phyllis", LastName = "Emerson" },
            new ClubUser { UserName = "BFV921uiT", Approved=true, Email ="lobortis@auctor.edu", FirstName = "Gavin", LastName = "Jennings" },
            new ClubUser { UserName = "BSm310OaN", Approved=true, Email ="quis@tortornibh.edu", FirstName = "Aquila", LastName = "Barrett" },
            new ClubUser { UserName = "mGj74BIoz", Approved=true, Email ="Integer.urna.Vivamus@ac.net", FirstName = "Sean", LastName = "Riggs" },
            new ClubUser { UserName = "BKF213AEY", Approved=false, Email ="Donec@necorciDonec.ca", FirstName = "Ryder", LastName = "Delacruz" },
            new ClubUser { UserName = "HQp81EAig", Approved=false, Email ="ante.ipsum.primis@laoreetlectus.net", FirstName = "Yoko", LastName = "Farmer" },
            new ClubUser { UserName = "HRj86CaEz", Approved=false, Email ="volutpat.Nulla@Donec.co.uk", FirstName = "Bertha", LastName = "Mullins" },
            new ClubUser { UserName = "pRs641uuM", Approved=true, Email ="velit.eu.sem@necligulaconsectetuer.com", FirstName = "Walter", LastName = "Sanchez" },
            new ClubUser { UserName = "OXB902OaR", Approved=true, Email ="sed@Integeridmagna.ca", FirstName = "Kendall", LastName = "Cain" },
            new ClubUser { UserName = "lLr18CeIf", Approved=true, Email ="auctor@nonjustoProin.ca", FirstName = "Urielle", LastName = "Barber" },
            new ClubUser { UserName = "GTG78Bioq", Approved=false, Email ="a.odio@euerat.org", FirstName = "Flavia", LastName = "Tillman" },
            new ClubUser { UserName = "jCS215uAp", Approved=false, Email ="enim.diam@turpis.ca", FirstName = "Gary", LastName = "Murray" },
            new ClubUser { UserName = "VGy280aeQ", Approved=false, Email ="Nullam.enim@etliberoProin.edu", FirstName = "Duncan", LastName = "Ellis" },
            new ClubUser { UserName = "SCN446IeV", Approved=true, Email ="est@laciniamattisInteger.ca", FirstName = "Ava", LastName = "Perry" },
            new ClubUser { UserName = "kNz71DoaZ", Approved=true, Email ="tempus.eu.ligula@semper.edu", FirstName = "Amela", LastName = "Anderson" },
            new ClubUser { UserName = "ySn873UeB", Approved=true, Email ="montes.nascetur.ridiculus@eu.net", FirstName = "Amery", LastName = "Rhodes" },
            new ClubUser { UserName = "hLk63BuIh", Approved=false, Email ="urna@nuncest.co.uk", FirstName = "Latifah", LastName = "Hicks" },
            new ClubUser { UserName = "jLk951aiS", Approved=false, Email ="scelerisque.mollis@tinciduntadipiscingMauris.ca", FirstName = "Dane", LastName = "Odonnell" },
            new ClubUser { UserName = "PQb61EeOx", Approved=false, Email ="massa.Mauris@Cumsociisnatoque.net", FirstName = "Tyler", LastName = "Murphy" },
            new ClubUser { UserName = "qZg758UeB", Approved=true, Email ="tortor.Nunc.commodo@nisiAenean.edu", FirstName = "Yael", LastName = "Holman" },
            new ClubUser { UserName = "JLx50FAUf", Approved=true, Email ="amet.faucibus.ut@elitCurabitur.net", FirstName = "Sonia", LastName = "Collier" },
            new ClubUser { UserName = "yWz963OOS", Approved=true, Email ="Curabitur@in.co.uk", FirstName = "Quinn", LastName = "Mays" },
            new ClubUser { UserName = "uWz337AID", Approved=false, Email ="nec.tellus@Vivamusnibhdolor.org", FirstName = "Noel", LastName = "Grant" },
            new ClubUser { UserName = "eSj602UUc", Approved=false, Email ="sit.amet.ornare@urnaNuncquis.org", FirstName = "Ferris", LastName = "Swanson" },
            new ClubUser { UserName = "oBq281EAM", Approved=false, Email ="mauris.ipsum@eteuismod.net", FirstName = "Kessie", LastName = "Duncan" },
            new ClubUser { UserName = "LXb360uot", Approved=true, Email ="sapien@velmaurisInteger.org", FirstName = "Cruz", LastName = "Thompson" },
            new ClubUser { UserName = "XGz349auz", Approved=true, Email ="vestibulum@vitaedolorDonec.com", FirstName = "Imani", LastName = "Evans" },
            new ClubUser { UserName = "TWJ656aER", Approved=true, Email ="et.ultrices@velitSedmalesuada.net", FirstName = "Levi", LastName = "Crane" },
            new ClubUser { UserName = "OJR74Ciiq", Approved=false, Email ="molestie.pharetra.nibh@ornareplaceratorci.com", FirstName = "Daria", LastName = "Kline" },
            new ClubUser { UserName = "EDD64EOoc", Approved=false, Email ="ligula.eu@ametnulla.org", FirstName = "Carissa", LastName = "Hendricks" },
            new ClubUser { UserName = "TSj883aAv", Approved=false, Email ="tristique.pharetra.Quisque@estNunc.com", FirstName = "Xavier", LastName = "Koch" },
            new ClubUser { UserName = "NWV78AiAH", Approved=true, Email ="Sed@lobortisaugue.com", FirstName = "Aimee", LastName = "Mayo" },
            new ClubUser { UserName = "yHm55AuAp", Approved=true, Email ="non.massa.non@turpisnec.org", FirstName = "Holly", LastName = "Walters" },
            new ClubUser { UserName = "BFd636eeG", Approved=true, Email ="elit.dictum.eu@faucibus.net", FirstName = "Felix", LastName = "Marks" },
            new ClubUser { UserName = "kSD419UAb", Approved=false, Email ="ullamcorper@et.edu", FirstName = "Connor", LastName = "Clarke" },
            new ClubUser { UserName = "SDk462EoS", Approved=false, Email ="nec.mauris.blandit@Inat.co.uk", FirstName = "Venus", LastName = "Kemp" },
            new ClubUser { UserName = "zCQ100Iib", Approved=false, Email ="amet.consectetuer.adipiscing@pharetraNamac.edu", FirstName = "Clark", LastName = "Wise" },
            new ClubUser { UserName = "xLn433eUx", Approved=true, Email ="lacinia@aliquamenim.org", FirstName = "Basil", LastName = "Mclaughlin" },
            new ClubUser { UserName = "nKp727aoc", Approved=true, Email ="ante.iaculis@Nullasemper.edu", FirstName = "Eden", LastName = "Harrison" },
            new ClubUser { UserName = "vGw460uut", Approved=true, Email ="et.magnis@gravidasitamet.co.uk", FirstName = "Oleg", LastName = "Carr" },
            new ClubUser { UserName = "tQF535Auh", Approved=false, Email ="aliquet.nec@Integereu.com", FirstName = "Lev", LastName = "Rivers" },
            new ClubUser { UserName = "KQs790aaN", Approved=false, Email ="ac@Namacnulla.com", FirstName = "Cassandra", LastName = "Mcgowan" },
            new ClubUser { UserName = "AMF311eef", Approved=false, Email ="amet@eratSednunc.ca", FirstName = "Abigail", LastName = "Glover" },
            new ClubUser { UserName = "xWb738Eor", Approved=true, Email ="lectus@ipsumcursus.ca", FirstName = "Conan", LastName = "Byers" },
            new ClubUser { UserName = "MBb86FoAr", Approved=true, Email ="Donec.tincidunt@Nullam.org", FirstName = "Dora", LastName = "Burnett" },
            new ClubUser { UserName = "xFy984AIF", Approved=true, Email ="ultrices@metus.net", FirstName = "Robin", LastName = "Rodriguez" },
            new ClubUser { UserName = "NSY94AAoy", Approved=false, Email ="euismod.in.dolor@nisi.co.uk", FirstName = "Neil", LastName = "Chaney" },
            new ClubUser { UserName = "jNn840iAL", Approved=false, Email ="eu.placerat@diam.co.uk", FirstName = "Jade", LastName = "Velasquez" },
            new ClubUser { UserName = "NFp79BoeV", Approved=false, Email ="vitae@velitdui.edu", FirstName = "Abbot", LastName = "Stein" },
            new ClubUser { UserName = "dMF209UEq", Approved=true, Email ="diam.Pellentesque.habitant@nislNullaeu.edu", FirstName = "Darius", LastName = "Padilla" },
            new ClubUser { UserName = "ZJG73Douk", Approved=true, Email ="ante.bibendum.ullamcorper@nec.com", FirstName = "Nita", LastName = "Bradley" },
            new ClubUser { UserName = "UHS263AOZ", Approved=true, Email ="eros@laciniaSedcongue.edu", FirstName = "Kibo", LastName = "Hoffman" },
            new ClubUser { UserName = "YYV17AIEc", Approved=false, Email ="ac.mattis.velit@malesuada.org", FirstName = "Matthew", LastName = "Todd" },
            new ClubUser { UserName = "XSv595Aux", Approved=false, Email ="Ut@Morbimetus.co.uk", FirstName = "Wyoming", LastName = "Petersen" },
            new ClubUser { UserName = "aTx516oEP", Approved=false, Email ="congue.turpis.In@Aliquamtincidunt.edu", FirstName = "Fleur", LastName = "Daugherty" },
            new ClubUser { UserName = "VWB382AeZ", Approved=true, Email ="sed.dolor.Fusce@idblanditat.ca", FirstName = "Zachary", LastName = "Fleming" },
            new ClubUser { UserName = "cJR534Oec", Approved=true, Email ="ultrices@intempuseu.com", FirstName = "Breanna", LastName = "Downs" },
            new ClubUser { UserName = "bWY67BouN", Approved=true, Email ="Cras.interdum@eueleifendnec.org", FirstName = "Fuller", LastName = "Ray" },
            new ClubUser { UserName = "BJH106Uiv", Approved=false, Email ="ac.mi@bibendum.org", FirstName = "Madonna", LastName = "Armstrong" },
            new ClubUser { UserName = "QBY76FAiF", Approved=false, Email ="venenatis.a@ornare.net", FirstName = "Eve", LastName = "Schmidt" },
            new ClubUser { UserName = "yNn64EIEH", Approved=false, Email ="mi.felis.adipiscing@Donecegestas.org", FirstName = "Buffy", LastName = "Reynolds" },
            new ClubUser { UserName = "QDc158UeN", Approved=true, Email ="malesuada@aliquetliberoInteger.ca", FirstName = "Kuame", LastName = "Garza" },
            new ClubUser { UserName = "gTw575UUC", Approved=true, Email ="vel@pedeac.com", FirstName = "Gemma", LastName = "Moses" },
            new ClubUser { UserName = "sWQ142oIr", Approved=true, Email ="tempus.lorem@ante.edu", FirstName = "Rhiannon", LastName = "Johnston" },
            new ClubUser { UserName = "ASR13EuUP", Approved=false, Email ="vitae.aliquet@convallisantelectus.edu", FirstName = "Francis", LastName = "Patel" },

        };
    }
}
